language: node_js
node_js:
  - '8'
  - '7'
  - '6'
before_install:
  - npm install -g yarn@0.27.5
install:
  - yarn install --pure-lockfile
script:
  - yarn test
env:
  global:
    secure: jKApC5Q+ccrj/4Kz4/nGIB0Y2mI7K9+kWlToeWHO3Lq7FWBITLBdyqO5PPf0Qs6dqzWeLOhtNXSkQ8ikZyvpweFJf2gX2gzAnXgVqtF03BFE0E5N/11BRrCOOE3aocYLqdAqto6AsWOmuIEh8pvX9KJyTw0mTFnBq8knVYVxsK5evBshUVDbSDrj+SiWLcuCge7FZXeBteQAzMKAIDycfFx60eRdKqLSjBRew7B2Wh2vJNoz57b6YVgfRTZkK4ZpoD7TvBzGhfT+gJmpe7GGP4XXVlMTuXi3kC0DgiGz/9oo1O5mjmBNRZaysoYeuxQ4d8Ix88zdmi5ydm3dt+pU7qhqICsZSXtntRlHh/wcThg++Aw9rgp59yLi1oMitWhE7YooXZ8+T75TQvisRSu6n8CN5vZ45O0hy6lQHsHtBYizrOsJS8UeRYVyr53DXyVb0AlfoTioF/6l3b90b8L+KnoCAIhWOc84ha58g0t7+nAkT67rfaeybTlOqBxDUh7LWHIpS2Enw2FjlFoApOIgtuP3HVokL3BCWvBp4Dw1v4dVRZtLGiLLoeMOSJv9NJA349I7roN1pRiBayGwkqUSVDZ/HupK8PRngdjeI/iH0NT7utQVKreOt5IXO4VE2VoTjG5KGYAtbygf9wfNTlmCKTFGc1hvZN1BCO0uW1qyuP0=
